<?php
/*
 * Copyright 2015 Stormpath, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Stormpath\Tests\Http\Helpers;

use Stormpath\Laravel\Http\Helpers\IdSiteRequest;
use Stormpath\Laravel\Http\Helpers\IdSiteSessionHelper;
use Stormpath\Laravel\Tests\TestCase;
use Stormpath\Stormpath;

class IdSiteRequestTest extends TestCase
{
    public function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app);
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setupStormpathApplication();
    }

    /** @test */
    public function it_can_set_all_items()
    {
        $idSiteRequest = new IdSiteRequest();

        $token = $idSiteRequest->setStormpathToken('hello');
        $this->assertInstanceOf('Stormpath\Laravel\Http\Helpers\IdSiteRequest', $token);

        $grantType = $idSiteRequest->setGrantType('stormpath_token');
        $this->assertInstanceOf('Stormpath\Laravel\Http\Helpers\IdSiteRequest', $grantType);
    }

    /** @test */
    public function it_can_get_all_items()
    {
        $idSiteRequest = new IdSiteRequest();

        $idSiteRequest->stormpathToken = 'hello';
        $this->assertEquals('hello', $idSiteRequest->stormpathToken);
        $this->assertEquals('hello', $idSiteRequest->getStormpathToken());

        $idSiteRequest->grantType = 'stormpath_token';
        $this->assertEquals('stormpath_token', $idSiteRequest->grantType);
        $this->assertEquals('stormpath_token', $idSiteRequest->getGrantType());
    }

    
}
