<?php
/*
 * Copyright 2015 Stormpath, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Stormpath\Tests\Http\Helpers;

use Stormpath\Laravel\Http\Helpers\IdSiteRequest;
use Stormpath\Laravel\Http\Helpers\IdSiteSessionHelper;
use Stormpath\Laravel\Tests\TestCase;
use Stormpath\Stormpath;

class IdSiteSessionHelperTest extends TestCase
{
    public function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app);
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setupStormpathApplication();
    }

    /** @test */
    public function it_can_create_an_id_site_session()
    {
        $account = $this->createAccount(['email'=>'test@test.com']);

        $idSite = new IdSiteSessionHelper();
        $session = $idSite->create($account);

        $this->assertInstanceOf('Stormpath\Resource\AccessToken', $session);

        $account->delete();

    }

    /** @test */
    public function it_throws_exception_if_id_site_session_can_not_be_created()
    {
        $account = $this->createAccount(['email'=>'test@test.com']);

        $account->delete();

        $idSite = new IdSiteSessionhelper();

        $this->setExpectedException('Stormpath\Laravel\Exceptions\SocialLoginException');
        $idSite->create($account);
    }

}
